# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _mystring
else:
    import _mystring

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class MyString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mystring.MyString_swiginit(self, _mystring.new_MyString(*args))

    def Length(self):
        return _mystring.MyString_Length(self)

    def Empty(self):
        return _mystring.MyString_Empty(self)

    def Clear(self):
        return _mystring.MyString_Clear(self)

    def CStr(self):
        return _mystring.MyString_CStr(self)

    def Data(self):
        return _mystring.MyString_Data(self)

    def Size(self):
        return _mystring.MyString_Size(self)

    def Capacity(self):
        return _mystring.MyString_Capacity(self)

    def ShrinkToFit(self):
        return _mystring.MyString_ShrinkToFit(self)

    def __add__(self, *args):
        return _mystring.MyString___add__(self, *args)

    def __iadd__(self, *args):
        return _mystring.MyString___iadd__(self, *args)

    def __lt__(self, string_object):
        return _mystring.MyString___lt__(self, string_object)

    def __le__(self, string_object):
        return _mystring.MyString___le__(self, string_object)

    def __gt__(self, string_object):
        return _mystring.MyString___gt__(self, string_object)

    def __ge__(self, string_object):
        return _mystring.MyString___ge__(self, string_object)

    def __eq__(self, string_object):
        return _mystring.MyString___eq__(self, string_object)

    def __ne__(self, string_object):
        return _mystring.MyString___ne__(self, string_object)

    def Insert(self, *args):
        return _mystring.MyString_Insert(self, *args)

    def Erase(self, index, count):
        return _mystring.MyString_Erase(self, index, count)

    def AppEnd(self, *args):
        return _mystring.MyString_AppEnd(self, *args)

    def Replace(self, *args):
        return _mystring.MyString_Replace(self, *args)

    def Substr(self, *args):
        return _mystring.MyString_Substr(self, *args)

    def Find(self, *args):
        return _mystring.MyString_Find(self, *args)
    __swig_destroy__ = _mystring.delete_MyString

    def __str__(self):
        return _mystring.MyString___str__(self)

# Register MyString in _mystring:
_mystring.MyString_swigregister(MyString)
cvar = _mystring.cvar
cMaxS = cvar.cMaxS
cMaxC = cvar.cMaxC
cSizeTable = cvar.cSizeTable
cAfterPoint = cvar.cAfterPoint

class PythString(MyString):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mystring.PythString_swiginit(self, _mystring.new_PythString(*args))

    def __add__(self, *args):
        return _mystring.PythString___add__(self, *args)

    def __lt__(self, string_object):
        return _mystring.PythString___lt__(self, string_object)

    def __gt__(self, string_object):
        return _mystring.PythString___gt__(self, string_object)

    def __le__(self, string_object):
        return _mystring.PythString___le__(self, string_object)

    def __ge__(self, string_object):
        return _mystring.PythString___ge__(self, string_object)

    def __eq__(self, string_object):
        return _mystring.PythString___eq__(self, string_object)

    def __ne__(self, string_object):
        return _mystring.PythString___ne__(self, string_object)

    def __iadd__(self, *args):
        return _mystring.PythString___iadd__(self, *args)
    __swig_destroy__ = _mystring.delete_PythString

    def __str__(self):
        return _mystring.PythString___str__(self)

    def __setitem__(self, i, symbol):
        return _mystring.PythString___setitem__(self, i, symbol)

    def __getitem__(self, i):
        return _mystring.PythString___getitem__(self, i)

# Register PythString in _mystring:
_mystring.PythString_swigregister(PythString)



